// Copyright (c) 2023 Migwi Ndung'u
// See LICENSE for details.

// Deployment configuration file is Auto generated - DO NOT EDIT.
// Code generated by "deployInfo" tool using the truffle deployment log;

package sapphirelocalnet

// GetNetwork returns the network used to make the deployment.
func GetNetwork() (string) {
	return "sapphire_localnet"
}

// GetBlockGasLimit returns the block gas limit set during deployment.
func GetBlockGasLimit() (string) {
	return "0xe4e1c0"
}

// GetChainID returns the chain ID of the network used to make the deployment.
func GetChainID() (uint64) {
	return 23293
}

// GetContractName returns the name of the contract deployed.
func GetContractName() (string) {
	return "ChatContract"
}

// GetContractAddress returns the address of the deployed contract.
func GetContractAddress() (string) {
	return "0x46BA6791dcB37499328eb1DDC116aF6dCd4EBE27"
}

// IsDeployed confirms if the contract was successfully deployed. If yes, it succeeded
func IsDeployed() (bool) {
	return true
}

// GetTransactionHash returns the tx hash when the contract we deployed.
func GetTransactionHash() (string) {
	return "0x9d54ed9aae37f3c46034a5a679cfca0c022e7e2b2da1e92c16f6d17bc3814ef1"
}

// GetDeploymentTime returns the timestamp in seconds when the contract was actually deployed 
func GetDeploymentTime() (uint64) {
	return 1692557885
}
