// Copyright (c) 2023 Migwi Ndung'u
// See LICENSE for details.

// Deployment configuration file is Auto generated - DO NOT EDIT.
// Code generated by "deployInfo" tool using the truffle deployment log;

package sapphirelocalnet

// GetNetwork returns the network used to make the deployment.
func GetNetwork() (string) {
	return ""
}

// GetBlockGasLimit returns the block gas limit set during deployment.
func GetBlockGasLimit() (string) {
	return ""
}

// GetChainID returns the chain ID of the network used to make the deployment.
func GetChainID() (uint64) {
	return 0
}

// GetContractName returns the name of the contract deployed.
func GetContractName() (string) {
	return ""
}

// GetContractAddress returns the address of the deployed contract.
func GetContractAddress() (string) {
	return ""
}

// IsDeployed confirms if the contract was successfully deployed. If yes, it succeeded
func IsDeployed() (bool) {
	return false
}

// GetTransactionHash returns the tx hash when the contract we deployed.
func GetTransactionHash() (string) {
	return ""
}

// GetDeploymentTime returns the timestamp in seconds when the contract was actually deployed 
func GetDeploymentTime() (uint64) {
	return 0
}
