// Copyright (c) 2023 Migwi Ndung'u
// See LICENSE for details.

// Deployment configuration file is Auto generated - DO NOT EDIT.
// Code generated by "deployinfo" tool using the truffle deployment log;

package sapphiremainnet

// GetNetwork returns the network used to make the deployment.
func GetNetwork() (string) {
	return ""
}

// GetBlockGasLimit returns the block gas limit set during deployment.
func GetBlockGasLimit() (uint64) {
	return 0
}

// GetChainID returns the chain ID of the network used to make the deployment.
func GetChainID() (uint64) {
	return 0
}

// GetContractAddress returns the address of the deployed contract.
func GetContractAddress() (string) {
	return ""
}

// GetTransactionHash returns the tx hash when the contract we deployed.
func GetTransactionHash() (string) {
	return ""
}

// GetDeploymentTime returns the timestamp in seconds when the contract was actually deployed 
func GetDeploymentTime() (uint64) {
	return 0
}

// GetDeploymentBlock returns the block number when the contract was actually deployed 
func GetDeploymentBlock() (uint32) {
	return 0
}
