// Copyright (c) 2023 Migwi Ndung'u
// See LICENSE for details.

// Deployment configuration file is Auto generated - DO NOT EDIT.
// Code generated by "deployInfo" tool using the truffle deployment log;

package sapphiretestnet

// GetNetwork returns the network used to make the deployment.
func GetNetwork() (string) {
	return "sapphire_testnet"
}

// GetBlockGasLimit returns the block gas limit set during deployment.
func GetBlockGasLimit() (uint64) {
	return 30000000
}

// GetChainID returns the chain ID of the network used to make the deployment.
func GetChainID() (uint64) {
	return 23295
}

// GetContractAddress returns the address of the deployed contract.
func GetContractAddress() (string) {
	return "0x3A46b54c82e2e1023c0C8638b079b4B5471c057F"
}

// GetTransactionHash returns the tx hash when the contract we deployed.
func GetTransactionHash() (string) {
	return "0xb4f1742a5eda1198dcd63237f1bbe55b6744fb47b10d6b02099be16ccd0c23e9"
}

// GetDeploymentTime returns the timestamp in seconds when the contract was actually deployed 
func GetDeploymentTime() (uint64) {
	return 1693133504
}

// GetDeploymentBlock returns the block number when the contract was actually deployed 
func GetDeploymentBlock() (uint64) {
	return 2368923
}
