// Copyright (c) 2023 Migwi Ndung'u
// See LICENSE for details.

// Deployment configuration file is Auto generated - DO NOT EDIT.
// Code generated by "deployInfo" tool using the truffle deployment log;

package sapphiretestnet

// GetNetwork returns the network used to make the deployment.
func GetNetwork() (string) {
	return "sapphire_testnet"
}

// GetBlockGasLimit returns the block gas limit set during deployment.
func GetBlockGasLimit() (string) {
	return "0x1c9c380"
}

// GetChainID returns the chain ID of the network used to make the deployment.
func GetChainID() (uint64) {
	return 23295
}

// GetContractName returns the name of the contract deployed.
func GetContractName() (string) {
	return "ChatContract"
}

// GetContractAddress returns the address of the deployed contract.
func GetContractAddress() (string) {
	return "0x262070cc136138f9b9452f5aAF7E7E20B637D05E"
}

// IsDeployed confirms if the contract was successfully deployed. If yes, it succeeded
func IsDeployed() (bool) {
	return true
}

// GetTransactionHash returns the tx hash when the contract we deployed.
func GetTransactionHash() (string) {
	return "0x772f55cac6e5703b0b49d7fd91c2bf27605c188f3dce81b40fdb648dc6412350"
}

// GetDeploymentTime returns the timestamp in seconds when the contract was actually deployed 
func GetDeploymentTime() (uint64) {
	return 1692566751
}
