// Copyright (c) 2023 Migwi Ndung'u
// See LICENSE for details.

// Deployment configuration file is Auto generated - DO NOT EDIT.
// Code generated by "deployInfo" tool using the truffle deployment log;

package sapphiretestnet

// GetNetwork returns the network used to make the deployment.
func GetNetwork() (string) {
	return "sapphire_testnet"
}

// GetBlockGasLimit returns the block gas limit set during deployment.
func GetBlockGasLimit() (uint64) {
	return 30000000
}

// GetChainID returns the chain ID of the network used to make the deployment.
func GetChainID() (uint64) {
	return 23295
}

// GetContractAddress returns the address of the deployed contract.
func GetContractAddress() (string) {
	return "0x22bB522c7356A8a6EAbd8ebd2B48d690FcB01787"
}

// GetTransactionHash returns the tx hash when the contract we deployed.
func GetTransactionHash() (string) {
	return "0xea8794eed416a9759d2cf646f139de2b3fbd0d25586dd9a76cbf02a20d5c906c"
}

// GetDeploymentTime returns the timestamp in seconds when the contract was actually deployed 
func GetDeploymentTime() (uint64) {
	return 1692704415
}

// GetDeploymentBlock returns the block number when the contract was actually deployed 
func GetDeploymentBlock() (uint32) {
	return 2310736
}
