// Copyright (c) 2023 Migwi Ndung'u
// See LICENSE for details.

// Deployment configuration file is Auto generated - DO NOT EDIT.
// Code generated by "deployInfo" tool using the truffle deployment log;

package development

// GetNetwork returns the network used to make the deployment.
func GetNetwork() (string) {
	return "development"
}

// GetBlockGasLimit returns the block gas limit set during deployment.
func GetBlockGasLimit() (string) {
	return "0x1c9c380"
}

// GetChainID returns the chain ID of the network used to make the deployment.
func GetChainID() (uint64) {
	return 1692555041599
}

// GetContractName returns the name of the contract deployed.
func GetContractName() (string) {
	return "ChatContract"
}

// GetContractAddress returns the address of the deployed contract.
func GetContractAddress() (string) {
	return "0x9Fce7b66875E539758450511180671A7042FF925"
}

// IsDeployed confirms if the contract was successfully deployed. If yes, it succeeded
func IsDeployed() (bool) {
	return true
}

// GetTransactionHash returns the tx hash when the contract we deployed.
func GetTransactionHash() (string) {
	return "0xcbed13fd870456fa038149aac07efe03fda40cb95fb0e18e55bb40d00fd01155"
}

// GetDeploymentTime returns the timestamp in seconds when the contract was actually deployed 
func GetDeploymentTime() (uint64) {
	return 1692555409
}
