name: contracts

on:
  push:
    paths:
      - 'contracts/**'
    branches:
      - main
  pull_request:
    paths:
      - 'contracts/**'
    branches:
      - main
  

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
       sapphire-dev-ci:
        image: ghcr.io/oasisprotocol/sapphire-dev:latest
        ports:
          - 8545:8545
          - 8546:8546
        env:
          OASIS_DEPOSIT: /oasis-deposit -to "refuse sport student pond weekend treat churn foot uniform bonus gaze science"
        options: >-
          --rm
          --health-cmd "/oasis-node debug control wait-ready -a unix:/serverdir/node/net-runner/network/client-0/internal.sock"
          --health-start-period 90s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: '8.x'
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Contracts Linter
        run: pnpm install

      - name: Run test contracts
        working-directory: contracts
        run: pnpm run test
